# this file will be used to use tests in the CICD pipeline
# Specify a base image
FROM node:12.13.0-alpine AS alpine

LABEL name='Chidubem' email='dubemnwabuisi@gmail.com'

WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package.json .

## install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm install
# Copy the contents of the project to the image
COPY . .
# Run 'npm start' when the container starts.
CMD ["npm", "run", "test"]